version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./ML
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - APP_URL=http://frontend:3000
    depends_on:
      - frontend
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
